# Generated by Django 3.1.7 on 2021-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudiobookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('uploaded_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AudiobookData',
            },
        ),
        migrations.CreateModel(
            name='PodcastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('uploaded_time', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PodcastData',
            },
        ),
        migrations.CreateModel(
            name='PodcastParticipantsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_id', models.CharField(max_length=100)),
                ('participant', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PodcastParticipantsData',
            },
        ),
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('uploaded_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SongData',
            },
        ),
    ]
