# Generated by Django 3.1.7 on 2021-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobookdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='podcastdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='podcastparticipantsdata',
            name='podcast_id',
        ),
        migrations.RemoveField(
            model_name='songdata',
            name='id',
        ),
        migrations.AddField(
            model_name='audiobookdata',
            name='file_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastdata',
            name='file_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastparticipantsdata',
            name='file_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdata',
            name='file_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
